name: CI

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Test
      run: go test -v -coverprofile="coverage.txt" ./...
    
    - name: Upload coverage reports to Codecov
      # upload coverage reports only once
      if: ${{ matrix.os == 'ubuntu' }} 
      uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
